# Run configuration example. See full config file spec in src/types/Configuration.d.ts

# Device trackers
## track android devices (default: true, if was INCLUDE_GOOG enabled in build config)
runGoogTracker: true
## track iOS devices (default: true, if was INCLUDE_APPL enabled in build config)
runApplTracker: true;

# HTTP[s] servers configuration
server:
    - secure: false
      port: 9410
wdaServerList:
    - udid: 00008101-00044CAE1A12001E
      localLinkAddress: 169.254.127.89
      wdaLocalPort: 8202
      mjpegServerPort: 9102
